### PR TITLE
Updates CSS styleguide README.md

### PR DESCRIPTION
**Pull request by janjaap**
Proposes changes for the following:
- Spaces (4 instead of 2)
- Using z-index
- Element selector usage
- Test hooks

### CODE REVIEW

**Comment by renancouto** [comment]
I think it is good specially the `z-index` and the element selector usage, but I disagree on the following:
- 2 spaces might be better if we will limit the line lengths (at 80 or 100 chars for instance)
- property alignment possibly generates more git diffs then it should

**Comment by janjaap** [comment]
@renancouto The implied line length is, for PHP, at 120 characters, so four spaces vs. two shouldn't matter. In my opinion, using four spaces is more readable then using two. Also the PHP guidelines uses four. So, to be consistent, I think we should use four spaces everywhere.
See https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md.
Property alignment also allows for more readable rule sets, IMHO. It only complicates diffs when the alignment is changed in a specific file.

**Comment by renancouto** [comment]
Alright @janjaap, if we are using 4 spaces in other places, then we should continue here.
I checked the linter and it catches this type of property alignment layout, so besides git diffing thing, they is nothing blocking us from applying that rule.
If the others are ok, we should update the examples on `README.md` according to this standards.

**Comment by janjaap** [comment]
Can you give an example of the problems that might arise with git diffs? Preferably code examples.

**Comment by tcboni** [comment]
2-space-indentation master race!

**Comment by renancouto** [comment]
@janjaap like [this](https://github.com/Endouble/friesland-campina/commit/87616fb06c7543d54d50532a1d03a35c145bee6a#diff-08352ea0f6be3493222df5dd4345ef5d) for instance. Looks like `color` and `padding-left` were completely changed, but their values actually remained the same.

**Comment by janjaap** [comment]
@renancouto I see your point. Ok, I'll remove the section about aligning properties and their values on the colon.

**Comment by janjaap** [comment]
@jeroennicolai @mozartdiniz What is your take on this?

**Comment by jeroennicolai** [comment]
I'm looking into it right now. Didn't get any messages from GIT Sorry

**Comment by jeroennicolai** [comment]
@janjaap @renancouto @tcboni @Buchie @mozartdiniz 
What about namespaces? We're already using js- and are going to introduce qa- but there's a whole list of goodness. http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/

**Pull request merged**
